### ISSUE TITLE
Feature Request: Add More Stacks to the Application

### ISSUE THREAD

**Issue by adokuru** [heycalebszn/bannerly#1]
More application stack offerings should include additional frameworks and languages. This will enhance the application’s versatility and cater to a broader range of users and developers.

• C
• Go (Golang)
• Flutter
• Rust
• Laravel (PHP Framework)
• C#
• Java
• .NET Framework

And others

**Comment by heyrapto** [comment]
Sure will do that right away!

**Comment by adokuru** [comment]
Can I contribute to it?
I just pulled and saw you have some icons

**Comment by heyrapto** [comment]
Sure, get the svgs from here

**Comment by heyrapto** [comment]
https://www.figma.com/design/fVoLvcGAXzUTAQMCWWdS7Q?fuid=1118290158653010572&prev-plan-id=1214336399687286587&prev-plan-type=team&prev-selected-view=recentsAndSharing
